# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(800, 600)
        Home.setAutoFillBackground(False)
        Home.setStyleSheet("")
        self.Central = QtWidgets.QWidget(Home)
        self.Central.setStyleSheet("")
        self.Central.setObjectName("Central")
        self.StartStop = QtWidgets.QPushButton(self.Central)
        self.StartStop.setEnabled(True)
        self.StartStop.setGeometry(QtCore.QRect(502, 355, 267, 82))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.StartStop.setFont(font)
        self.StartStop.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.StartStop.setStyleSheet("background-color: rgba(43, 11, 11,0.5);\n"
"border-radius:20;\n"
"color: rgb(249,35,35);\n"
"font: 63 14.5pt \"Poppins SemiBold\";\n"
"\n"
"")
        self.StartStop.setObjectName("StartStop")
        self.Logo = QtWidgets.QLabel(self.Central)
        self.Logo.setGeometry(QtCore.QRect(50, 28, 207, 55))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Logo.setFont(font)
        self.Logo.setStyleSheet("color:white;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"")
        self.Logo.setObjectName("Logo")
        self.Profile = QtWidgets.QToolButton(self.Central)
        self.Profile.setGeometry(QtCore.QRect(663, 33, 43, 43))
        self.Profile.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:21px;\n"
"icon-size:25px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/assets/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Profile.setIcon(icon)
        self.Profile.setObjectName("Profile")
        self.Setting = QtWidgets.QToolButton(self.Central)
        self.Setting.setGeometry(QtCore.QRect(718, 33, 43, 43))
        self.Setting.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:21px;\n"
"icon-size:25px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/assets/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Setting.setIcon(icon1)
        self.Setting.setObjectName("Setting")
        self.Avg = QtWidgets.QFrame(self.Central)
        self.Avg.setGeometry(QtCore.QRect(502, 108, 267, 119))
        self.Avg.setStyleSheet("background-color: rgba(19, 19, 19,    0.7);\n"
"border-radius:20px;")
        self.Avg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Avg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Avg.setObjectName("Avg")
        self.Week = QtWidgets.QFrame(self.Central)
        self.Week.setGeometry(QtCore.QRect(502, 239, 267, 102))
        self.Week.setStyleSheet("background-color: rgba(19, 19, 19,    0.7);\n"
"border-radius:20px;")
        self.Week.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Week.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Week.setObjectName("Week")
        self.Graph = QtWidgets.QFrame(self.Central)
        self.Graph.setGeometry(QtCore.QRect(31, 108, 458, 329))
        self.Graph.setStyleSheet("background-color: rgba(19, 19, 19,    0.7);\n"
"border-radius:20px;")
        self.Graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Graph.setObjectName("Graph")
        self.TimerLabel = QtWidgets.QLabel(self.Central)
        self.TimerLabel.setGeometry(QtCore.QRect(43, 450, 210, 44))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.TimerLabel.setFont(font)
        self.TimerLabel.setStyleSheet("color:white;\n"
"font-size: 14.5pt;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.TimerLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TimerLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TimerLabel.setWordWrap(False)
        self.TimerLabel.setObjectName("TimerLabel")
        self.Pause = QtWidgets.QToolButton(self.Central)
        self.Pause.setGeometry(QtCore.QRect(678, 498, 43, 43))
        self.Pause.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:21px;\n"
"icon-size:20px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/assets/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Pause.setIcon(icon2)
        self.Pause.setObjectName("Pause")
        self.Reset = QtWidgets.QToolButton(self.Central)
        self.Reset.setGeometry(QtCore.QRect(726, 498, 43, 43))
        self.Reset.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:21px;\n"
"icon-size:20px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/assets/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Reset.setIcon(icon3)
        self.Reset.setObjectName("Reset")
        self.min50 = QtWidgets.QSlider(self.Central)
        self.min50.setGeometry(QtCore.QRect(143, 498, 530, 43))
        self.min50.setStyleSheet("Qslider::groove:horizontal{\n"
"height:43px;\n"
"}    ")
        self.min50.setOrientation(QtCore.Qt.Horizontal)
        self.min50.setObjectName("min50")
        self.min10 = QtWidgets.QSlider(self.Central)
        self.min10.setGeometry(QtCore.QRect(32, 498, 106, 43))
        self.min10.setOrientation(QtCore.Qt.Horizontal)
        self.min10.setObjectName("min10")
        self.Name = QtWidgets.QFrame(self.Central)
        self.Name.setGeometry(QtCore.QRect(586, 38, 119, 32))
        self.Name.setStyleSheet("background-color: rgba(19, 19, 19,    0.7);\n"
"border-radius:15px\n"
";")
        self.Name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Name.setObjectName("Name")
        self.Background = QtWidgets.QLabel(self.Central)
        self.Background.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap(":/newPrefix/b1.png"))
        self.Background.setObjectName("Background")
        self.Background.raise_()
        self.Name.raise_()
        self.StartStop.raise_()
        self.Logo.raise_()
        self.Setting.raise_()
        self.Avg.raise_()
        self.Week.raise_()
        self.Graph.raise_()
        self.TimerLabel.raise_()
        self.Pause.raise_()
        self.Reset.raise_()
        self.min50.raise_()
        self.min10.raise_()
        self.Profile.raise_()
        Home.setCentralWidget(self.Central)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.StartStop.setText(_translate("Home", "Stop Tracking"))
        self.Logo.setText(_translate("Home", "Just Blink"))
        self.Profile.setText(_translate("Home", "..."))
        self.Setting.setText(_translate("Home", "..."))
        self.TimerLabel.setText(_translate("Home", "Pomodoro Timer"))
        self.Pause.setText(_translate("Home", "..."))
        self.Reset.setText(_translate("Home", "..."))
import app_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
